#!/bin/bash

# Working: Increment/Decrement using intervals of 5 in the range (5, 95)
# For [0,5] && [95, 100] increment/decrement using intervals of 1

get_brightness(){
    brightness="$(xbacklight)"
    format_brightness
}

format_brightness(){
    brightness=$(printf "%.2f" $brightness)
}

increase_brightness(){
    get_brightness

    case $brightness in
        95.00) xbacklight -set 96;;
        96.00) xbacklight -set 97;;
        97.00) xbacklight -set 98;;
        98.00) xbacklight -set 99;;
        99.00) xbacklight -set 100;;
        100.00) ;;

        *)  increment_by_5
            xbacklight -set $brightness;;
    esac
}

increment_by_5(){
    brightness=$(echo "print(($brightness / 5 + 1) * 5)" | python3)
    brightness=$(echo "print(5 * round($brightness / 5))" | python3)
}

decrease_brightness(){
    get_brightness
    echo $brightness

    case $brightness in
        5.00) xbacklight -set 4;;
        4.00) xbacklight -set 3;;
        3.00) xbacklight -set 2;;
        2.00) xbacklight -set 1;;
        1.00) xbacklight -set 0.5;;
        0.50) xbacklight -set 0.25;;
        0.25) xbacklight -set 0;;
        0) ;;

        *) decrement_by_5
           xbacklight -set $brightness;;
    esac
}

decrement_by_5(){
    brightness=$(echo "print(($brightness / 5 - 1) * 5)" | python3)
    brightness=$(echo "print(5 * round($brightness / 5))" | python3)
}

if [ $1 == "-inc" ]; then
    increase_brightness
    volnoti-show -b $brightness
elif [ $1 == "-dec" ]; then
    decrease_brightness
    volnoti-show -b $brightness
else
    echo "Unknown error encountered"
fi
