#!/bin/bash

# Calling the script from xmonad on caps_lock press is inefficient:
# It requires a delay(0.1/0.2) so that the caps_lock value is set properly; without the delay the value returned is always "on"
#

update_caps(){
    caps_status="$(xset q | grep "Caps" | awk -F' ' '{ print $4 }')"
}

show_indicator(){
    if [ "$1" == "on" ]; then
        volnoti-show -p "$VOLNOTI_IMAGE_DIR/capsLocked.svg" -t "Caps Locked" -f "Fira Code 14" 101
    else
        volnoti-show -p "$VOLNOTI_IMAGE_DIR/capsUnlocked.svg" -t "Caps Unlocked" -f "Fira Code 14" 101
    fi
}

## Script execution begins

VOLNOTI_IMAGE_DIR=/usr/share/pixmaps/volnoti
prev_caps_status="$(xset q | grep "Caps" | awk -F' ' '{ print $4 }')"

# Sleep value performance:
# 0.05: 1.2 - 1.9(avg), 3.0% cpu
# 0.06: 0.7 - 1.3 (avg), 2.0 (max)
# 0.07: 0.6 - 1.3(avg), 1.3 (max)
# 0.08: 0.6 - 1.3(avg), 2.0(max)

while sleep 0.10; do
    update_caps

    if [ "$caps_status" != "$prev_caps_status" ]; then
        prev_caps_status="$caps_status"
        show_indicator "$caps_status"
    fi

done

