#!/bin/bash

increment_val=2

volnotify(){
    toggle_status=$(awk -F"[][]" '/Left:/ { print $4 }' <(amixer sget Master))
    volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))

    if [ "$toggle_status" == "on" ];then
        volnoti-show $volume
    else
        volnoti-show -m $volume
    fi
}

increase_volume(){
    amixer -q set Master $increment_val%+ && volnotify
}

decrease_volume(){
    amixer -q set Master $increment_val%- && volnotify
}

toggle_mute(){
    amixer -q set Master toggle && volnotify
}

navigatenotify(){
    if [ "$1" == "--next" ]; then
        volnoti-show -p "/usr/share/pixmaps/volnoti/previous.svg"
    elif [ "$1" == "--prev" ]; then
        volnoti-show -p "/usr/share/pixmaps/volnoti/next.svg"
    fi
}

playnotify(){
    local status="$1"

    if [ "$status" == "Playing" ]; then
        volnoti-show -p "/usr/share/pixmaps/volnoti/play.svg"
    elif [ "$status" == "Paused" ]; then
        volnoti-show -p "/usr/share/pixmaps/volnoti/pause.svg"
    else
        :
    fi
}

toggle_play_pause(){
    status="$(playerctl status)"

    # If media is currently playing, then play_pause will pause it
    # So show the opposite icon
    if [ "$status" == "Playing" ]; then
        status="Paused"
    elif [ "$status" == "Paused" ]; then
        status="Playing"
    else
        status=""
    fi

    playerctl play-pause && playnotify "$status"
}

toggle_mic(){
    ## Based on https://askubuntu.com/a/1291627
    
    # Get active audio source index
    CURRENT_SOURCE=$(pactl info | grep "Default Source" | cut -f3 -d" ")

    # List lines in pactl after the source name match and pick mute status
    status=$(pactl list sources | grep -A 10 $CURRENT_SOURCE)

    # requires GNU grep
    muted=$(echo "$status" | grep -oP '(?<=Mute:\s)\w+')
    echo "$muted"

    mic_volume=($(echo "$status" | grep -Eo 1?[0-9][0-9]%))
    echo ${mic_volume[0]}

    if [ "$muted" == "no" ] ; then
        amixer set Capture nocap && 
        volnoti-show -p "/usr/share/pixmaps/volnoti/mic_muted.svg" $mic_volume
    else
        amixer set Capture cap &&
        volnoti-show -p "/usr/share/pixmaps/volnoti/mic_on.svg" $mic_volume
    fi

}

if [ "$1" == "--inc" ]; then
    increase_volume
elif [ "$1" == "--dec" ]; then
    decrease_volume
elif [ "$1" == "--toggle_mute" ]; then
    toggle_mute
elif [ "$1" == "--play-pause" ]; then
    toggle_play_pause
elif [ "$1" == "--next" ]; then
    playerctl next && navigatenotify "$1"
elif [ "$1" == "--prev" ]; then
    playerctl previous && navigatenotify "$1"
elif [ "$1" == "--toggle_mic_mute" ]; then
    toggle_mic
else
    echo "Unknown error encountered"
fi
