#!/bin/bash

SOURCE_DIRECTORY=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )


# Ensure multiple processes are not running
killall -q auto-nitrogen > /dev/null
if [ $? -eq 0 ]; then
    time=($(date))
    $SOURCE_DIRECTORY/nitrologger "${time[*]}" "killed"
fi

exec $SOURCE_DIRECTORY/auto-nitrogen
