swipe:
  4:
    up:
      command: 'xdotool key XF86AudioRaiseVolume'
      interval: 0.1
      threshold: 0.1
    down:
      command: 'xdotool key XF86AudioLowerVolume'
      interval: 0.1
      threshold: 0.1
  3:
    left:
      command: 'xdotool key super+Left'
      interval: 0.5
      threshold: 0.5
    right:
      command: 'xdotool key super+Right'
      interval: 0.5
      threshold: 0.5
